### ISSUE TITLE
CI/CD?

### ISSUE THREAD

**Issue by Restioson** [Restioson/flower#14]
Should we set up a CI? Travis perhaps? We could make this nice 'n strict by failing builds which clippy errors on and rustfmt finds weird formatting in.

**Comment by Restioson** [comment]
@gegy1000 should we use travis? Perhaps your jenkins?

**Comment by gegy1000** [comment]
Travis is probably simpler for now -- if we get to a stage where we need artifacts to be available, we could move to Jenkins. What do you think? Maybe we should just go for Jenkins right away?

**Comment by Restioson** [comment]
Hmm... I've only used Travis, and don't really know how Jenkins works. What would be the difference?

**Comment by gegy1000** [comment]
Travis simply tests build success. Jenkins does this and hosts built artifacts. The builds also have to be managed on the Jenkins server.

**Comment by Restioson** [comment]
Hmm... What do you think? Jenkins might be easier since it Flower requires quite a few build dependencies.

**Comment by gegy1000** [comment]
They're probably about the same when it comes to setting up.

**Comment by Restioson** [comment]
@gegy1000 perhaps we could use Jenkins, so we could also allow people to download builds.

**Comment by Restioson** [comment]
@gegy1000 this is done, so if you could just add badges, links, and integrate this with github (or tell me what I need to do for that to be done) then that would be great and we can close this.

**Comment by Restioson** [comment]
Namely, [this commit](https://github.com/Restioson/flower/commit/817fd9bb9a1bd802aa0343ef7ae979ada6bb36f2)
