### ISSUE TITLE
Use bitflags

### ISSUE THREAD

**Issue by Restioson** [Restioson/flower#16]
Much of the code in flower could be improved by use of the [bitflags](https://github.com/rust-lang-nursery/bitflags) crate. We should use this.

**Comment by gegy1000** [comment]
I'll do a general PS/2 cleanup, which will address this along with #18

**Comment by Restioson** [comment]
:+1:

**Comment by gegy1000** [comment]
Is there anywhere else that bitflags should be used? All cases have been addressed for PS/2.

**Comment by Restioson** [comment]
I think PS/2 is basically it. Perhaps it could be used in keyboard for storing key modifiers?

**Comment by Restioson** [comment]
However, I consider this closed, as this was about existing code. Closing.
