### ISSUE TITLE
Come up with a good RFC/proposal process?

### ISSUE THREAD

**Issue by Restioson** [Restioson/flower#22]
I think it would be beneficial to come up with an rfc/proposal process so we can have discussion before we begin implementing big things. Any ideas on how this would work?

**Comment by Restioson** [comment]
@gegy1000 could I have your input here?

**Comment by gegy1000** [comment]
At this early stage of the project I don't believe this is necessary yet.

**Comment by Restioson** [comment]
It could be useful since I would like to formally discuss and finalize the port IPC, I think.

**Comment by gegy1000** [comment]
We could possibly post issues here for it with a [proposal] tag?

**Comment by Restioson** [comment]
That would probably be adequate for now. I'll close this until it becomes apparent that we need a better solution.
