### ISSUE TITLE
Policy on obselete feature support?

### ISSUE THREAD

**Issue by Restioson** [Restioson/flower#24]
We need to decide whether Flower will aim to support obsolete features, such as black and white screens. 

Supporting obsolete features such as PS/2 has the advantage that more people can use flower. **Case in point:** @gegy1000 owns and uses a PS/2 keyboard.

However, supporting these features can complicate and bloat design and APIs. **Case in point:** the terminal driver (#12) would need to have many extra traits -- e.g `ColoredTerminal`, `ColoredSizedTerminal`, and this could introduce more complexity -- for instance, `ColoredSizedTerminal` could automatically implement `Terminal`, `ColoredTerminal`, `SizedTerminal`, etc, which makes it massively more complex, ugly and bloated.

Alternatively, we could justify supporting features on a case-by-case basis, or do something else. Thoughts?

**Comment by Restioson** [comment]
Personally, I am with the case-by-case basis. If the net gain for supporting a feature is negative, then we don't implement it. If it is positive, we implement it.

**Comment by gegy1000** [comment]
I agree with you on choosing case-by-case. However, I think the design of code like you explain should be  reconsidered. Ideally, we want it to be scaleable.

**Comment by Restioson** [comment]
I agree. Where should we put a note about this decision?

**Comment by Restioson** [comment]
Closing. I will move this into a doc file
