### ISSUE TITLE
Backspacing off the screen makes you go down a line

### ISSUE THREAD

**Issue by Restioson** [Restioson/flower#53]
Steps to reproduce:
    - Boot
    - Hold backspace. Observe that when x = 0 and backspace is pressed, the cursor moves down a line and not up

Shouldn't be hard to fix.

**Comment by gegy1000** [comment]
Seems to be fixed on the PS2-enhancements branch

**Comment by Restioson** [comment]
Cool. We'll close this when it's merged.
