### ISSUE TITLE
ACPI tracking issue

### ISSUE THREAD

**Issue by Restioson** [Restioson/flower#61]
I've started work on ACPI. 

- [x] RSDP V1/V2
- [x] RSDT/XSDT
- [x] MADT
- [x] HPET
- [ ] FACP
- [ ] AML
- [ ] (Other tables... add pls)

How much of this should we merge into master before 0.2.0?

**Comment by Restioson** [comment]
Re: 
> How much of this should we merge into master before 0.2.0?

Perhaps not AML, but what more tables?

**Comment by gegy1000** [comment]
What would AML be required for? If not too much, then yeah, we should probably leave it for later.

**Comment by Restioson** [comment]
The main reason I pose this question is because ACPI is *big*. The spec is a thousand words long. AML is the bytecode of AML, and tbh I don't see myself completing it in the same timeframe as of PS/2, interrupts, and memory management.

**Comment by gegy1000** [comment]
In that case, we should definitely merge in before it's fully complete. It's not worth spending long waiting for ACPI and letting that hold everything else up.

**Comment by Restioson** [comment]
Yeah. It's in another (local) branch currently.

**Comment by Restioson** [comment]
Maybe let's merge when HPET is done?

**Comment by Restioson** [comment]
Cool. @Gegy1000 did hpet, but now I'm thinking we should do FACP before we merge, so we can tell if PS/2 controller is there for the ps2 branch. I can do that sometime, or maybe gegy can, I don't particularly mind.

**Comment by phil-opp** [comment]
Hi, we're also currently working on an ACPI implementation at [rust-osdev/acpi](https://github.com/rust-osdev/acpi). Maybe we can combine forces?

cc @rust-osdev/acpi

**Comment by gegy1000** [comment]
@phil-opp Sounds great! :)

**Comment by Restioson** [comment]
Yeah! What can we do to help? Perhaps we can add the HPET code to the crate. What needs to be done, otherwise? I was looking at AML the other day, so I could try help with that perhaps. I've started a bit of work on a local branch.

**Comment by phil-opp** [comment]
Cool! I sent you two an invitation to the organization.

> What can we do to help?

The two people currently working on it are @IsaacWoods and @Sh4d1, so they should be able to answer it best.

**Comment by Restioson** [comment]
Update: I am working on integrating the crate into flower now in the acpi-crate branch.
